#!/usr/bin/env python3
# Generate the FEATURE-GATED embedded prelude for the self-hosted `machin`.
# Go emits the runtime prelude as core (cRuntime+net+tty, always) followed by
# per-feature blocks appended in a fixed order, each gated by a uses<X> flag. We
# recover each block by subtraction:  prelude(feature) - prelude(core) = block.
# The prelude of a program = (machin build --emit-c) minus (machin cgentest --program),
# since the full C is exactly prelude + program-body and the body is the suffix.
#
# Emits selfhost/cgprelude.src: base64 constants CG_PRELUDE_<F> + a gated emit_prelude(body).
import base64, subprocess, os, sys, tempfile

MACHIN = os.environ.get("MACHIN", "./bin/machin")

def run(args, inp=None):
    return subprocess.run(args, capture_output=True, text=True).stdout

def prelude_of(src):
    """prelude bytes for a program source string = full_emit_c - body."""
    with tempfile.NamedTemporaryFile("w", suffix=".src", delete=False) as f:
        f.write(src); p = f.name
    mfl = p + ".mfl"
    open(mfl, "w").write(run([MACHIN, "encode", p]))
    full = run([MACHIN, "build", mfl, "--emit-c"])
    body = run([MACHIN, "cgentest", "--program", mfl])
    os.unlink(p); os.unlink(mfl)
    assert full.endswith(body), "full C does not end with the body — cannot subtract"
    return full[: len(full) - len(body)]

# feature-triggering programs (each uses exactly one feature family)
FEAT = {
    "CORE":   'func main(){write(1,"x")}',
    "MATH":   'func main(){write(1,str(sqrt(2.0)))}',
    "NOISE":  'func main(){write(1,str(noise2(1.0,2.0)))}',
    "REGEX":  'func main(){write(1,str(regex_match("a","a")))}',
    "SQLITE": 'func main(){h:=sqlite_open(":memory:")  sqlite_close(h)}',
    "CRYPTO": 'func main(){write(1,to_hex(rand_bytes(4)))}',
    "TLS":    'func main(){s,b,e:=http_get("https://x")  write(1,b+str(s)+e)}',
    "WSS":    'func main(){h:=wss_open("wss://x")  wss_close(h)}',
    "TLSWSS": 'func main(){s,b,e:=http_get("https://x")  h:=wss_open("wss://y")  write(1,b+str(s)+e+str(h))}',
    # use bytes() (core), NOT rand_bytes (crypto), so the XEDDSA block is xeddsaRuntime
    # ALONE — otherwise it also carries cryptoRuntime and double-emits with the crypto block.
    "XEDDSA": 'func main(){write(1,to_hex(xeddsa_sign(bytes("a"),bytes("b"),bytes("c"))))}',
}

pre = {k: prelude_of(v) for k, v in FEAT.items()}
core = pre["CORE"]
blocks = {}
for k in FEAT:
    if k == "CORE":
        blocks[k] = core
        continue
    assert pre[k].startswith(core), f"{k} prelude does not start with CORE"
    blocks[k] = pre[k][len(core):]

# split TLS/WSS: both carry tlsCore. Recover its length EXACTLY by inclusion-exclusion
# (P_tls+wss = core + tlsCore + tls + wss), not by common-prefix (which over-extends when
# tls/wss share a leading line): len(tlsCore) = len(P_tls)+len(P_wss)-len(core)-len(P_tls+wss).
tlscore_len = len(pre["TLS"]) + len(pre["WSS"]) - len(core) - len(pre["TLSWSS"])
assert 0 <= tlscore_len <= len(blocks["TLS"]), f"bad tlscore_len {tlscore_len}"
blocks["TLSCORE"] = blocks["TLS"][:tlscore_len]
assert blocks["WSS"][:tlscore_len] == blocks["TLSCORE"], "tlsCore mismatch between TLS and WSS"
tls_only = blocks["TLS"][tlscore_len:]
wss_only = blocks["WSS"][tlscore_len:]
blocks["TLS"] = tls_only
blocks["WSS"] = wss_only
del blocks["TLSWSS"]

order = ["CORE", "TLSCORE", "TLS", "WSS", "MATH", "NOISE", "REGEX", "SQLITE", "CRYPTO", "XEDDSA"]
out = ["// selfhost/cgprelude.src — GENERATED by gen-prelude.py. The runtime prelude, split",
       "// into feature blocks (recovered by subtraction from the Go compiler). Emission is",
       "// gated by the g_uses_* flags in compile.src's emit_prelude_gated(), matching Go's",
       "// uses<X> gating byte-for-byte. Do not edit by hand.",
       ""]
for k in order:
    b64 = base64.b64encode(blocks[k].encode()).decode()
    out.append(f'var CG_PRELUDE_{k} = "{b64}"')
out.append("")
open("selfhost/cgprelude.src", "w").write("\n".join(out) + "\n")
sizes = {k: len(blocks[k]) for k in order}
print("wrote cgprelude.src; block sizes:", sizes)
