#!/usr/bin/env bash
# Reproducible fib(40) benchmark: MFL (native) vs hand-written C vs Rust.
#
# Produces the table in the README "Performance" section on YOUR machine, so the
# numbers are verifiable rather than asserted. Absolute times depend on hardware;
# what matters is that MFL lands in the same class as the C it compiles to.
#
# Usage:  examples/bench/run_bench.sh [runs]
#   runs  number of timed repetitions per implementation (default 5; best is kept)
#
# Requires: go, a C compiler (cc/gcc/clang). Rust (rustc) is optional and skipped
# if absent. Run from the repository root or from examples/bench/.
set -euo pipefail

RUNS="${1:-5}"

# Resolve repo root relative to this script so it works from any CWD.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

CC="${CC:-cc}"

echo "machin fib(40) benchmark — best of $RUNS runs"
echo "host: $(uname -s) $(uname -m)"
echo

# --- Build the machin toolchain --------------------------------------------
echo "building machin toolchain..."
( cd "$ROOT" && go build -trimpath -o "$WORK/machin" . )

# --- Compile each implementation to a native binary -------------------------
echo "compiling fib (MFL / C / Rust)..."
# machin prints a "built ..." line to stderr; keep the harness output clean but
# still surface real failures (set -e aborts on a non-zero build).
"$WORK/machin" build "$SCRIPT_DIR/fib.mfl" -o "$WORK/fib_mfl" >/dev/null 2>&1
"$CC" -O2 "$SCRIPT_DIR/fib.c" -o "$WORK/fib_c"

HAVE_RUST=0
if command -v rustc >/dev/null 2>&1; then
    rustc -O "$SCRIPT_DIR/fib.rs" -o "$WORK/fib_rs"
    HAVE_RUST=1
fi
echo

# --- Metric helpers ---------------------------------------------------------
# best_time: best wall-clock seconds over $RUNS executions (millisecond res).
best_time() {
    local bin="$1" best="" t
    local TIMEFORMAT='%R'   # bash `time` keyword honours this shell variable
    for _ in $(seq "$RUNS"); do
        # `time` writes only the real-time seconds (%R) to stderr.
        t="$( { time "$bin" >/dev/null; } 2>&1 )"
        if [ -z "$best" ] || awk "BEGIN{exit !($t < $best)}"; then best="$t"; fi
    done
    printf '%s' "$best"
}

# bin_size: stripped-binary size, human-readable (e.g. "16K").
bin_size() { du -h "$1" | cut -f1; }

# peak_rss: peak resident set size via GNU `/usr/bin/time -v`; "n/a" if absent.
peak_rss() {
    local bin="$1" kb
    if [ -x /usr/bin/time ]; then
        kb="$(/usr/bin/time -v "$bin" 2>&1 >/dev/null \
              | awk -F': ' '/Maximum resident set size/ {print $2}')"
        [ -n "$kb" ] && { awk "BEGIN{printf \"%.1f MB\", $kb/1024}"; return; }
    fi
    printf 'n/a'
}

# Verify all implementations agree on the answer before trusting the timings.
EXPECT="$("$WORK/fib_mfl")"
[ "$("$WORK/fib_c")" = "$EXPECT" ] || { echo "C output mismatch!" >&2; exit 1; }
if [ "$HAVE_RUST" = 1 ]; then
    [ "$("$WORK/fib_rs")" = "$EXPECT" ] || { echo "Rust output mismatch!" >&2; exit 1; }
fi

# --- Collect metrics --------------------------------------------------------
MFL_T="$(best_time "$WORK/fib_mfl")"; MFL_SZ="$(bin_size "$WORK/fib_mfl")"; MFL_RSS="$(peak_rss "$WORK/fib_mfl")"
C_T="$(best_time "$WORK/fib_c")";     C_SZ="$(bin_size "$WORK/fib_c")";     C_RSS="$(peak_rss "$WORK/fib_c")"
if [ "$HAVE_RUST" = 1 ]; then
    RS_T="$(best_time "$WORK/fib_rs")"; RS_SZ="$(bin_size "$WORK/fib_rs")"; RS_RSS="$(peak_rss "$WORK/fib_rs")"
fi

# --- Emit the report (markdown) ---------------------------------------------
# Written to $REPORT (default examples/bench/BENCHMARKS.md) and echoed to stdout.
REPORT="${REPORT:-$SCRIPT_DIR/BENCHMARKS.md}"
{
    echo "# Benchmark report — fib(40)"
    echo
    echo "Generated by \`examples/bench/run_bench.sh\` (best of $RUNS runs)."
    echo "Numbers are **machine-dependent**; reproduce with \`make bench-report\`."
    echo
    echo "- host: \`$(uname -s) $(uname -m)\`"
    echo "- workload: \`fib(40)\` naive recursion (~331M calls), result \`$EXPECT\`"
    echo
    echo "| Implementation          | Time   | Binary | Peak RSS | Notes |"
    echo "|-------------------------|--------|--------|----------|-------|"
    printf '| %-23s | %5ss | %-6s | %-8s | emits C, optimized by cc -O2 |\n' "MFL (native, cc -O2)" "$MFL_T" "$MFL_SZ" "$MFL_RSS"
    printf '| %-23s | %5ss | %-6s | %-8s | the baseline MFL compiles to |\n' "hand-written C (cc -O2)" "$C_T" "$C_SZ" "$C_RSS"
    if [ "$HAVE_RUST" = 1 ]; then
        printf '| %-23s | %5ss | %-6s | %-8s | for reference (rustc -O) |\n' "Rust" "$RS_T" "$RS_SZ" "$RS_RSS"
    else
        echo "| Rust                    | —      | —      | —        | rustc not found — skipped |"
    fi
} | tee "$REPORT"

echo
echo "report written to ${REPORT/#$ROOT\//}"
