#!/usr/bin/env bash
# Reproducible benchmark: naive fib(40) across three compilers.
#
#   MFL  -> C -> cc -O2   (what `machin build` does)
#   C    -> cc -O2        (hand-written reference, examples/bench/fib.c)
#   Rust -> rustc -O      (hand-written reference, examples/bench/fib.rs)
#
# Each binary is built, sanity-checked (must print 102334155), then run N times
# (BENCH_RUNS, default 5). We keep the best wall-clock time, peak RSS, and the
# stripped-ish on-disk binary size, and regenerate docs/BENCHMARKS.md.
#
# Numbers are machine-dependent — the point is that anyone can reproduce the
# *shape* of the comparison on their own box with `make bench-report`.
set -euo pipefail

cd "$(dirname "$0")/.."

N="${BENCH_RUNS:-5}"
OUT="docs/BENCHMARKS.md"
EXPECT="102334155"
TIME_BIN="${TIME_BIN:-/usr/bin/time}"
MACHIN="bin/machin"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

if [ ! -x "$TIME_BIN" ]; then
  echo "error: GNU time not found at $TIME_BIN (set TIME_BIN=...)" >&2
  exit 1
fi

if [ ! -x "$MACHIN" ]; then
  echo "building toolchain..." >&2
  make build >/dev/null
fi

# Ordered list of "label|binary" entries that actually built.
ENTRIES=()

echo "compiling MFL -> C -> native (machin build)..." >&2
"$MACHIN" build examples/bench/fib.mfl -o "$WORK/fib_mfl"
ENTRIES+=("MFL (native, cc -O2)|$WORK/fib_mfl")

if command -v cc >/dev/null 2>&1; then
  echo "compiling hand-written C (cc -O2)..." >&2
  cc -O2 -o "$WORK/fib_c" examples/bench/fib.c
  ENTRIES+=("hand-written C (cc -O2)|$WORK/fib_c")
else
  echo "skipping C: cc not on PATH" >&2
fi

if command -v rustc >/dev/null 2>&1; then
  echo "compiling Rust (rustc -O)..." >&2
  rustc -O -o "$WORK/fib_rs" examples/bench/fib.rs
  ENTRIES+=("Rust (rustc -O)|$WORK/fib_rs")
else
  echo "skipping Rust: rustc not on PATH" >&2
fi

# seconds_of "<h:mm:ss or m:ss.ss>" -> floating seconds
seconds_of() {
  echo "$1" | awk -F: '{ if (NF==3) print $1*3600+$2*60+$3; else if (NF==2) print $1*60+$2; else print $1 }'
}

# measure "<binary>" -> echoes "best_seconds peak_rss_kb"
measure() {
  local bin="$1" best="" rss="" i out wall kb
  for i in $(seq 1 "$N"); do
    out="$("$TIME_BIN" -v "$bin" 2>&1 >/dev/null)"
    wall="$(echo "$out" | awk -F'): ' '/Elapsed \(wall clock\)/{print $2}')"
    wall="$(seconds_of "$wall")"
    kb="$(echo "$out" | awk -F': ' '/Maximum resident set size/{print $2}')"
    if [ -z "$best" ] || awk "BEGIN{exit !($wall < $best)}"; then
      best="$wall"; rss="$kb"
    fi
  done
  echo "$best $rss"
}

ROWS=""
for entry in "${ENTRIES[@]}"; do
  label="${entry%%|*}"
  bin="${entry#*|}"

  got="$("$bin")"
  if [ "$got" != "$EXPECT" ]; then
    echo "error: $label produced '$got', expected '$EXPECT'" >&2
    exit 1
  fi

  read -r secs rss < <(measure "$bin")
  size="$(stat -c %s "$bin")"
  printf -v secs_fmt "%.3f" "$secs"
  rss_mb="$(awk "BEGIN{printf \"%.1f\", $rss/1024}")"
  size_kb="$(awk "BEGIN{printf \"%.0f\", $size/1024}")"
  echo "  $label: ${secs_fmt}s  ${rss_mb} MB RSS  ${size_kb} KB" >&2
  ROWS="${ROWS}| ${label} | ${secs_fmt}s | ${rss_mb} MB | ${size_kb} KB |
"
done

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
# Benchmark report — naive fib(40)

Generated by [\`scripts/bench.sh\`](../scripts/bench.sh); regenerate with:

\`\`\`bash
make bench-report          # or: BENCH_RUNS=10 scripts/bench.sh
\`\`\`

All three contenders run the **same algorithm** — doubly-recursive
\`fib(40)\` (= ${EXPECT}, ~331M calls) — so this is a compiler-vs-compiler
comparison, not an algorithmic one:

- **MFL** — \`machin build examples/bench/fib.mfl\` (MFL → C → \`cc -O2\`)
- **C** — hand-written [\`examples/bench/fib.c\`](../examples/bench/fib.c), \`cc -O2\`
- **Rust** — hand-written [\`examples/bench/fib.rs\`](../examples/bench/fib.rs), \`rustc -O\`

Best of ${N} runs. Time is wall-clock; RSS is peak resident set; size is the
on-disk binary. **Numbers are machine-dependent** — they come from whatever
box ran the script. Reproduce them on yours rather than trusting these.

| Implementation | Time (best of ${N}) | Peak RSS | Binary size |
|----------------|---------------------|----------|-------------|
${ROWS}
> MFL lowers to ordinary C, so its native binary lands in the same ballpark as
> hand-written C — the remaining gap is codegen overhead, not interpretation.
EOF

echo "wrote $OUT" >&2
